highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
environment: prod
url: "http://127.0.0.1:4000/"

future: false
show_drafts: false

plugins:
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-katex
  - jekyll-toc
katex:
  js_path: "assets"  # Path used to search for katex.min.js
  rendering_options:
    throw_error: false
    error_color: "#cc0000"
toc:
  min_level: 1
  max_level: 3
  ordered_list: false
